<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="85" started-at="2019-12-11T06:32:43Z" finished-at="2019-12-11T06:32:43Z">
    <groups>
      <group name="smoke">
        <method signature="TestClass001.method1()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method1" class="com.tests.TestClass001"/>
        <method signature="TestClass001.method2()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method2" class="com.tests.TestClass001"/>
      </group> <!-- smoke -->
      <group name="Regression">
        <method signature="TestClass001.method3()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method3" class="com.tests.TestClass001"/>
        <method signature="TestClass001.method4()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method4" class="com.tests.TestClass001"/>
        <method signature="TestClass001.method5()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method5" class="com.tests.TestClass001"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="TestClass001.method5()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method5" class="com.tests.TestClass001"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Test" duration-ms="85" started-at="2019-12-11T06:32:43Z" finished-at="2019-12-11T06:32:43Z">
      <class name="com.tests.TestClass001">
        <test-method status="PASS" signature="Login1()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="Login1" duration-ms="22" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login1 -->
        <test-method status="FAIL" signature="Login2()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="Login2" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.tests.TestClass001.Login2(TestClass001.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login2 -->
        <test-method status="PASS" signature="method5()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method5" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method5 -->
        <test-method status="PASS" signature="method3()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method3" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
        <test-method status="SKIP" signature="Login3()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="Login3" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[ Don't say bye]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException:  Don't say bye
	at com.tests.TestClass001.Login3(TestClass001.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login3 -->
        <test-method status="PASS" signature="method2()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method2" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method2 -->
        <test-method status="PASS" signature="method4()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method4" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method4 -->
        <test-method status="PASS" signature="method1()[pri:0, instance:com.tests.TestClass001@3cb5cdba]" name="method1" duration-ms="0" started-at="2019-12-11T12:02:43Z" finished-at="2019-12-11T12:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method1 -->
      </class> <!-- com.tests.TestClass001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
